In [1]:
from Bio import SeqIO
import os

In [16]:
import os
from Bio import SeqIO

fastas = []

# 폴더 내의 fasta 파일 중 앞의 2개만 처리
for fasta_file in os.listdir(r'D:\minimax\binding_affinity\질환관련 fasta'):
    disease_name = fasta_file.split('.')[0]
    fasta_file_name = os.path.join(r'D:\minimax\binding_affinity\질환관련 fasta', fasta_file)
    sequences = {}
    for record in SeqIO.parse(fasta_file_name, "fasta"):
        protein_id = record.id        # 단백질 ID (예: P00533)
        sequence = str(record.seq)    # 아미노산 서열
        sequences['타겟 질환'] = disease_name
        sequences['fasta'] = sequence
    fastas.append(sequences)   # print는 루프 밖에서 한 번만 출력

In [17]:
import pandas as pd 
fasta_info = pd.DataFrame(fastas)
fasta_info.head()

  타겟 질환                                              fasta
0  B형간염  MAEGEGYFAMSEDELACSPYIPLGGDFGGGDFGGGDFGGGDFGGGG...
1  C형간염  MSTNPKPQRKKPNVTPTVAHRTSSSRVAVRSLVEFTCCRAGALDWV...
2    간암  MQSKVLLAVALWLCVETRAASVGLPSVSLDLPRLSIQKDILTIKAN...
3   고혈압  MGAASGRRGPGLLLPLPLLLLLPPQPALALDPGLQPGNFSADEAGA...
4   뇌전증  MEQTVLVPPGPDSFNFFTRESLAAIERRIAEEKAKNPKPDKKDDDE...

In [18]:
fasta_info.to_csv('for_binding_affinity_predict.csv',index=False)

In [19]:
fasta_info.head()

  타겟 질환                                              fasta
0  B형간염  MAEGEGYFAMSEDELACSPYIPLGGDFGGGDFGGGDFGGGDFGGGG...
1  C형간염  MSTNPKPQRKKPNVTPTVAHRTSSSRVAVRSLVEFTCCRAGALDWV...
2    간암  MQSKVLLAVALWLCVETRAASVGLPSVSLDLPRLSIQKDILTIKAN...
3   고혈압  MGAASGRRGPGLLLPLPLLLLLPPQPALALDPGLQPGNFSADEAGA...
4   뇌전증  MEQTVLVPPGPDSFNFFTRESLAAIERRIAEEKAKNPKPDKKDDDE...

In [ ]:
fasta_info = pd.read_csv('for_binding_affinity_predict.csv')

for new_smiles in [신약 후보 물질 smiles]:
    predict값 = []
    for target_fast in fasta_info['fasta']:
        BA값 = model.predict(new_smiles, target_fast)
        predict값.append(BA값)
    print(min(predict값)) # 만약 치매 쪽에서 제일 작은 값이 나오면 해당 물질은 치매 치료제에 제일 적합한 것

In [ ]:
# 분자 생성 완료 후 저장
{
	'new_molecule_ID' : 'MOLECULE01', # 고유 ID(중복 방지), Chembl_ID랑 다름!
	'new_canonical_smiles' : 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C', # 새로운 분자 smiles
    'new_smiles_scaffold' : 'COc1cccc2c1C(=O)', # 새로운 분자 핵심 구조
    'new_molecule_image' : '', # 분자 이미지
    'new_disease_type' : '폐암' # 이건 입력값으로 들어온 scaffold 데이터의 disease type과 동일
}