In [1]:
treatment_smiles = {
    "위암": {
        "Tegafur": "CC1(CO)C(=O)NC(=O)N1",
        "Trifluridine": "C1=NC(=O)NC(=N1)C2=CC=C(C=C2)F",
        "Fluorouracil": "C1=CNC(=O)NC1=O"
    },
    "간암": {
        "Sorafenib": "CC(C)NC1=NC=C(C=C1)C(=O)NC2=CC=C(C=C2)OC3=CC=C(C=C3)Cl",
		"Regorafenib": "CC(C)NC1=NC=C(C=C1)C(=O)NC2=CC=C(C=C2)OC3=CC=C(C=C3)C(=O)N4CCCCC4",
		"Cabozantinib": "CN(C)C(=O)C1=NC(=CC(=C1)NC2=CC=C(C=C2)OC)C3=CC=CC=C3C#N"
    },
    "자궁경부암": {
        "Paclitaxel": "CC1=C2C(=O)OC(C(C2=O)OC3C(C(C(C(O3)CO)O)O)OC(=O)C4=CC=CC=C4)C5=CC=CC=C51",
        "Topotecan": "COC1=CC2=C(C=C1)C(=O)OC3C2C4C(=O)N(C)CC4OC3=O"
    },
    "대장암": {
        "Irinotecan": "CC1=C2C(=O)OC3C(C2=O)C(=O)N(C)CC3OC1=O"
    },
    "유방암": {
        "Tamoxifen": "CC/C(=C(/C1=CC=CC=C1)C2=CC=CC=C2)C3=CC=C(C=C3)OCCN(C)C",
		"Letrozole": "CC1=NN=C(N=C1)C2=CC=CC=C2C#N",
		"Lapatinib": "CS(=O)(=O)CCNC1=CC=C(C=C1)C2=NC3=CC(=C(C=C3N2)OC4=CC=CC=C4F)Cl"
    },
    "에이즈 (HIV)": {
        "Zidovudine": "CC1=CN(C2=NC=NC(=O)C2N)C(=O)N1",
        "Efavirenz": "O=C1NC(=O)C2=CC(=CC=C2C1=O)C#CC3=CC=CC=C3",
        "Nevirapine": "CC1=NC(=O)NC2=CC=CC=C12"
    },
    "코로나19": {
        "Remdesivir": "CC(C)C[C@H](C(=O)O[C@H]1O[C@@H](CN2C=NC3=C2N=CN=C3N)C(O)[C@H]1O)NC(=O)C4=CC=CC=C4",
        "Molnupiravir": "CC1(C)OC(=O)NC(CO)C(O)C1O",
    },
    "인플루엔자": {
        "Oseltamivir": "CCOC(=O)C[C@@H](C=C(CO)NC(C)=O)C1CC1",
        "Zanamivir": "NC1C(C(C(C(O1)C(=O)O)O)O)NC2=C(C=CC(=O)N2)C(=O)O",
        "Baloxavir marboxil": "CCOC(=O)COC(=O)C1=C(C=CC(=C1)O)C(=O)OCC2=CC=CC=C2"
    },
    "B형 간염": {
        "Entecavir": "C1=NC2C(=CN1)O[C@H](CO)[C@@H](O)C2",
        "Tenofovir": "CC(C)COCP(=O)(O)OCC1=CN=C(N1)N",
        "Lamivudine": "C1=CN(C(=O)NC1=O)[C@H]2O[C@@H](CO)[C@H](O)[C@H]2O"
    },
    "C형 간염": {
        "Sofosbuvir": "CCC(=O)OC[C@H]1O[C@H](CN2C=NC3=C2N=CN=C3N)C(O)[C@H]1O",
        "Velpatasvir": "CC1=CC(=O)NC(=O)N1C2=CC=C(C=C2)OC3=CC=C(C=C3)CF",
        "Glecaprevir": "CC(C)(C)NC(=O)C1C(C2=CC=CC=C2)NC(=O)N1C3CCCCC3"
    },
    "뇌전증": {
        "Valproic acid": "CCCC(CCC)C(=O)O",
        "Carbamazepine": "C1=CC=C2C(=C1)C(=O)N(C2=O)C3=CC=CC=C3",
        "Lamotrigine": "C1=CC(=CC(=C1)Cl)NC2=NC(=NC=N2)N"
    },
    "치매": {
        "Donepezil": "CC1=CC=CC=C1C2=CC=CC=C2C(=O)N3CCN(CC3)C4=CC=CC=C4",
        "Rivastigmine": "CCOC(=O)N(C)C1CCCCC1",
        "Memantine": "CC12CCC(CC1)CC(C2)N"
    },
    "뇌졸중": {
        "Aspirin": "CC(=O)OC1=CC=CC=C1C(=O)O",
        "Clopidogrel": "COC(=O)C1=CC=CC=C1SCC2=NC=NC3=C2C=CC=C3",
        "Atorvastatin": "CC(C)C[C@@H](C(=O)O)N1CCC2=C(C1)C=CC=C2O"
    },
    "파킨슨병": {
        "Levodopa": "C1=CC(=C(C=C1O)O)C(C(=O)O)N",
        "Selegiline": "CC(C)CC#CCN(C)C",
        "Rasagiline": "C1CC2=CC=CC=C2N1C"
    },
    "당뇨": {
        "Metformin": "CNC(=N)NC(=N)N",
        "Empagliflozin": "CC1=CC(=CC=C1O)C2OC(CO)C(O)C(O)C2O",
        "Pioglitazone": "CC1=CC=C(C=C1)COC2=CC=C(C=C2)C(=O)NCC3CCCO3"
    },
    "고혈압": {
        "Losartan": "CC1=CC=CC=C1C(=O)N2CCCCC2C(=O)NCC3=CC=C(C=C3)OC",
        "Amlodipine": "CC1=CC(=O)OC2=C(C1)C(=CC=C2)OC",
        "Valsartan": "CC(C)C1=NC(=O)NC2=CC=CC=C12C(=O)OCC3=CC=CC=C3"
    }
}

In [2]:
import pandas as pd
 
df = (
    pd.DataFrame([
        {"질병": disease, "치료제": drug, "SMILES": smiles}
        for disease, drugs in treatment_smiles.items()
        for drug, smiles in drugs.items()
    ])
)

# 보기 좋게 정렬
df = df.sort_values(by=["질병", "치료제"]).reset_index(drop=True)
df.head()

      질병          치료제                                             SMILES
0  B형 간염    Entecavir                 C1=NC2C(=CN1)O[C@H](CO)[C@@H](O)C2
1  B형 간염   Lamivudine  C1=CN(C(=O)NC1=O)[C@H]2O[C@@H](CO)[C@H](O)[C@H]2O
2  B형 간염    Tenofovir                     CC(C)COCP(=O)(O)OCC1=CN=C(N1)N
3  C형 간염  Glecaprevir     CC(C)(C)NC(=O)C1C(C2=CC=CC=C2)NC(=O)N1C3CCCCC3
4  C형 간염   Sofosbuvir  CCC(=O)OC[C@H]1O[C@H](CN2C=NC3=C2N=CN=C3N)C(O)...

In [ ]:
from minimax_backend.prediction_all import make_smiles

remove_lst = []

for smiles in df['SMILES']:
    try:
        make_smiles(smiles)
    except:
        remove_lst.append(smiles)

c:\Users\amysm\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Skipped loading modules with pytorch-geometric dependency, missing a dependency. No module named 'torch_geometric'
Skipped loading modules with pytorch-geometric dependency, missing a dependency. cannot import name 'DMPNN' from 'deepchem.models.torch_models' (c:\Users\amysm\AppData\Local\Programs\Python\Python310\lib\site-packages\deepchem\models\torch_models\__init__.py)
Skipped loading modules with pytorch-lightning dependency, missing a dependency. No module named 'lightning'
Skipped loading some Jax models, missing a dependency. No module named 'haiku'
Some weights of EsmModel were not initialized from the model checkpoint at facebook/esm2_t6_8M_UR50D and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of RobertaModel were not initialized from the model checkpoint at DeepChem/ChemBERTa-77M-MLM and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
c:\Users\amysm\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
[22:52:36] Explicit valence for atom # 13 C, 5, is greater than permitted

In [4]:
df = df[~df['SMILES'].isin(remove_lst)]

In [5]:
df = df.drop_duplicates('SMILES')
df = df.reset_index()

In [6]:
df = df.drop('index',axis=1)
df.head()

      질병           치료제                                             SMILES
0  B형 간염     Entecavir                 C1=NC2C(=CN1)O[C@H](CO)[C@@H](O)C2
1  B형 간염     Tenofovir                     CC(C)COCP(=O)(O)OCC1=CN=C(N1)N
2  C형 간염   Glecaprevir     CC(C)(C)NC(=O)C1C(C2=CC=CC=C2)NC(=O)N1C3CCCCC3
3  C형 간염   Velpatasvir    CC1=CC(=O)NC(=O)N1C2=CC=C(C=C2)OC3=CC=C(C=C3)CF
4     간암  Cabozantinib  CN(C)C(=O)C1=NC(=CC(=C1)NC2=CC=C(C=C2)OC)C3=CC...

In [7]:
df_unique = df.drop_duplicates(subset=["질병"], keep="first").reset_index(drop=True)
df_unique.head()

      질병            치료제                                             SMILES
0  B형 간염      Entecavir                 C1=NC2C(=CN1)O[C@H](CO)[C@@H](O)C2
1  C형 간염    Glecaprevir     CC(C)(C)NC(=O)C1C(C2=CC=CC=C2)NC(=O)N1C3CCCCC3
2     간암   Cabozantinib  CN(C)C(=O)C1=NC(=CC(=C1)NC2=CC=C(C=C2)OC)C3=CC...
3    고혈압     Amlodipine                     CC1=CC(=O)OC2=C(C1)C(=CC=C2)OC
4    뇌전증  Carbamazepine              C1=CC=C2C(=C1)C(=O)N(C2=O)C3=CC=CC=C3

In [8]:
from rdkit import Chem
from rdkit.Chem.Draw import rdMolDraw2D
import base64, json

def smiles_to_svg_base64(smiles: str, size=(300, 300)) -> str:
    mol = Chem.MolFromSmiles(smiles)
    drawer = rdMolDraw2D.MolDraw2DSVG(size[0], size[1])
    rdMolDraw2D.PrepareAndDrawMolecule(drawer, mol)
    drawer.FinishDrawing()
    svg = drawer.GetDrawingText()
    # Base64 인코딩
    return base64.b64encode(svg.encode("utf-8")).decode("utf-8")

In [9]:
from chembl_webresource_client.new_client import new_client

molecule = new_client.molecule
df_unique[['d_chembl_id','d_name','d_canosmiles','d_formula','d_type','d_image_base64']] = None

for i in range(len(df_unique)):
    drug_name = df_unique.loc[i, '치료제']
    res = molecule.filter(pref_name__icontains=drug_name)
    
    if res:
        mol = res[0]
        df_unique.loc[i, 'd_chembl_id'] = mol.get("molecule_chembl_id")
        df_unique.loc[i, 'd_name'] = mol.get("pref_name")
        df_unique.loc[i, 'd_canosmiles'] = mol["molecule_structures"]["canonical_smiles"]
        df_unique.loc[i, 'd_formula'] = mol.get("molecule_properties", {}).get("full_molformula")
        df_unique.loc[i, 'd_type'] = mol.get("molecule_type")

In [14]:
df_unique.columns

Index(['질병', '치료제', 'SMILES', 'd_chembl_id', 'd_name', 'd_canosmiles',
       'd_formula', 'd_type', 'd_image_base64'],
      dtype='object')

In [15]:
df_unique = df_unique.rename(columns={'질병':'d_detail_category'})
df_unique.head()

,d_detail_category,치료제,SMILES,d_chembl_id,d_name,d_canosmiles,d_formula,d_type,d_image_base64
0,B형 간염,Entecavir,C1=NC2C(=CN1)O[C@H](CO)[C@@H](O)C2,CHEMBL713,ENTECAVIR ANHYDROUS,C=C1[C@H](CO)[C@@H](O)C[C@@H]1n1cnc2c(=O)[nH]c...,C12H15N5O3,Small molecule,None
1,C형 간염,Glecaprevir,CC(C)(C)NC(=O)C1C(C2=CC=CC=C2)NC(=O)N1C3CCCCC3,CHEMBL3545363,GLECAPREVIR,CC(C)(C)[C@@H]1NC(=O)O[C@@H]2CCC[C@H]2OC/C=C/C...,C38H46F4N6O9S,Small molecule,None
2,간암,Cabozantinib,CN(C)C(=O)C1=NC(=CC(=C1)NC2=CC=C(C=C2)OC)C3=CC...,CHEMBL2103868,CABOZANTINIB S-MALATE,COc1cc2nccc(Oc3ccc(NC(=O)C4(C(=O)Nc5ccc(F)cc5)...,C32H30FN3O10,Small molecule,None
3,고혈압,Amlodipine,CC1=CC(=O)OC2=C(C1)C(=CC=C2)OC,CHEMBL1491,AMLODIPINE,CCOC(=O)C1=C(COCCN)NC(C)=C(C(=O)OC)C1c1ccccc1Cl,C20H25ClN2O5,Small molecule,None
4,뇌전증,Carbamazepine,C1=CC=C2C(=C1)C(=O)N(C2=O)C3=CC=CC=C3,CHEMBL108,CARBAMAZEPINE,NC(=O)N1c2ccccc2C=Cc2ccccc21,C15H12N2O,Small molecule,None

In [17]:
df_unique = df_unique.drop(['치료제', 'SMILES'],axis=1)
df_unique.head()

,d_detail_category,d_chembl_id,d_name,d_canosmiles,d_formula,d_type,d_image_base64
0,B형 간염,CHEMBL713,ENTECAVIR ANHYDROUS,C=C1[C@H](CO)[C@@H](O)C[C@@H]1n1cnc2c(=O)[nH]c...,C12H15N5O3,Small molecule,None
1,C형 간염,CHEMBL3545363,GLECAPREVIR,CC(C)(C)[C@@H]1NC(=O)O[C@@H]2CCC[C@H]2OC/C=C/C...,C38H46F4N6O9S,Small molecule,None
2,간암,CHEMBL2103868,CABOZANTINIB S-MALATE,COc1cc2nccc(Oc3ccc(NC(=O)C4(C(=O)Nc5ccc(F)cc5)...,C32H30FN3O10,Small molecule,None
3,고혈압,CHEMBL1491,AMLODIPINE,CCOC(=O)C1=C(COCCN)NC(C)=C(C(=O)OC)C1c1ccccc1Cl,C20H25ClN2O5,Small molecule,None
4,뇌전증,CHEMBL108,CARBAMAZEPINE,NC(=O)N1c2ccccc2C=Cc2ccccc21,C15H12N2O,Small molecule,None

In [18]:
df_unique['d_category'] = None

In [19]:
def categorize(detail):
    if detail in ['위암', '간암', '자궁경부암', '대장암', '유방암']:
        return '암 치료제'
    elif detail in ['에이즈 (HIV)', '코로나19', '인플루엔자', 'B형 간염', 'C형 간염']:
        return '항바이러스제'
    elif detail in ['뇌전증', '치매', '뇌졸중', '파킨슨병']:
        return '신경 질환'
    else:
        return '대사 질환'

df_unique['d_category'] = df_unique['d_detail_category'].apply(categorize)

In [21]:
df_unique['d_image_base64'] = df_unique['d_canosmiles'].apply(smiles_to_svg_base64)

In [25]:
df_unique.to_csv('버튼별 분자 정보.csv',index=False)